FROM bitwalker/alpine-elixir:1.5.2

# TODO Why do we have libgcc and libstdc++ here?
RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ bash && \
    rm -rf /var/cache/apk/*

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD ${APP}.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/${APP}"]
